# -*- coding: utf-8 -*-
"""randopt_1d.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SsBrfQ-iFKuGElWjTNiFoX4dtMaCzCGy

# RandOpt Tutorial: 1D Signal Experiments

This notebook has two parts:

* **Algorithm**: an overview of the RandOpt (Neural Thickets) procedure.
* **Toy Example**: a 1D signal prediction experiment to demonstrate how it works.

**The toy experiments in this notebook reproduce similar behaviors to those we observe in LLMs with RandOpt, including the three regimes discussed in the main paper: needle-in-a-haystack, thicket, and plateau.**
"""

import copy
import random
import time

import numpy as np
import torch
import torch.nn as nn
import matplotlib.pyplot as plt

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Device: {device}")

"""## 1. The Model

A simple MLP that takes a context window of past values and predicts the next value. The two key methods for RandOpt are:

- `perturb_weights(seed, sigma)` — adds reproducible Gaussian noise to all parameters
- `AR_rollout(ctx, T)` — autoregressively predicts T future steps
"""

class Net(nn.Module):
    def __init__(self, width, depth, dim_in, dim_out, init_type, device):
        super().__init__()
        self.width, self.depth = width, depth
        self.dim_in, self.dim_out = dim_in, dim_out
        self.device = device
        self.init_type = init_type

        layers = [nn.Linear(dim_in, width, device=device)]
        for _ in range(depth - 2):
            layers.extend([nn.ReLU(), nn.Linear(width, width, device=device)])
        layers.extend([nn.ReLU(), nn.Linear(width, dim_out, device=device)])
        self.layers = nn.ModuleList(layers)

    def forward(self, ctx):
        was_1d = ctx.dim() == 1
        if was_1d:
            ctx = ctx.unsqueeze(0)
        h = ctx
        for layer in self.layers:
            h = layer(h)
        if was_1d:
            h = h.squeeze(0)
        return h.squeeze(-1)

    def compute_loss(self, ctx, y):
        y_pred = self.forward(ctx)
        return nn.MSELoss()(y_pred, y.squeeze(-1))

    def init_weights(self):
        for layer in self.layers:
            if isinstance(layer, nn.Linear):
                if self.init_type == "xavier":
                    nn.init.xavier_uniform_(layer.weight)
                elif self.init_type == "kaiming init":
                    nn.init.kaiming_uniform_(layer.weight)
                elif self.init_type == "ortho":
                    nn.init.orthogonal_(layer.weight)
                else:
                    raise ValueError(f"Invalid init type: {self.init_type}")
                nn.init.zeros_(layer.bias)

    def perturb_weights(self, seed, sigma):
        """Add reproducible Gaussian noise to all parameters.
        The same (seed, sigma) always produces the same perturbation."""
        torch.manual_seed(seed)
        for p in self.parameters():
            p.data.add_(torch.randn_like(p.data) * sigma)

    def AR_rollout(self, ctx, T):
        """Autoregressive rollout: predict T steps into the future."""
        y_preds = []
        for t in range(T):
            y_pred = self.forward(ctx)
            ctx = torch.cat([ctx, y_pred.unsqueeze(-1)], dim=1)[:, 1:]
            y_preds.append(y_pred)
        return torch.stack(y_preds, dim=1)

"""## 2. Synthetic 1D Datasets

We generate 1D signals (lines, sinusoids, square waves, etc.) as toy tasks. Each sample has a context window and a future window to predict.
"""

FREQ = 4.0
SCALE = 1.0

def generate_line():
    slope = np.random.uniform(-0.5, 0.5)
    intercept = np.random.uniform(-1.0, 1.0)
    return lambda x: slope * x + intercept

def generate_one_line():
    return lambda x: -0.25 * x + 0.0

def generate_sinusoid():
    phase = np.random.uniform(0, 2 * np.pi)
    amp = np.random.uniform(0.8, 1.2)
    y_offset = np.random.uniform(-0.5, 0.5)
    def fn(x):
        x = np.asarray(x)
        return amp * np.sin(FREQ * x + phase) + y_offset
    return fn

def generate_one_sinusoid():
    def fn(x):
        x = np.asarray(x)
        return 0.5 * np.sin(FREQ * x)
    return fn

def generate_squarewave():
    phase = np.random.uniform(0, 2 * np.pi)
    amp = np.random.uniform(0.2, 0.4)
    y_offset = np.random.uniform(-0.5, 0.5)
    sharpness = np.random.uniform(4.0, 6.0)
    def fn(x):
        x = np.asarray(x)
        return amp * np.tanh(sharpness * np.sin(FREQ * x + phase)) + y_offset
    return fn

def generate_one_squarewave():
    def fn(x):
        x = np.asarray(x)
        return 0.3 * np.tanh(5.0 * np.sin(FREQ * x))
    return fn

def generate_sawtooth():
    phase = np.random.uniform(0, 2 * np.pi)
    amp = np.random.uniform(0.8, 1.2)
    y_offset = np.random.uniform(-0.5, 0.5)
    def fn(x):
        x = np.asarray(x)
        t = FREQ * x + phase
        saw = np.sin(t) - 0.5 * np.sin(2 * t) + 0.33 * np.sin(3 * t) - 0.25 * np.sin(4 * t)
        return amp * saw * 0.5 + y_offset
    return fn

def generate_harmonic():
    phase = np.random.uniform(0, 2 * np.pi)
    amp = np.random.uniform(0.8, 1.2)
    y_offset = np.random.uniform(-0.5, 0.5)
    def fn(x):
        x = np.asarray(x)
        return amp * (0.5 * np.sin(FREQ * x + phase) + 0.3 * np.sin(2 * FREQ * x)) + y_offset
    return fn

def generate_sigmoid():
    phase = np.random.uniform(0, 2 * np.pi) - np.pi
    amp = np.random.uniform(0.5, 1.5)
    y_offset = np.random.uniform(-0.5, 0.5)
    def fn(x):
        x = np.asarray(x)
        return amp * np.tanh(0.1 * x + phase) + y_offset
    return fn

def generate_mixed():
    generators = [generate_sinusoid, generate_squarewave, generate_sawtooth,
                  generate_harmonic, generate_sigmoid, generate_line]
    return np.random.choice(generators)()

DATASET_GENERATORS = {
    "line": generate_line, "one_line": generate_one_line,
    "sinusoid": generate_sinusoid, "one_sinusoid": generate_one_sinusoid,
    "squarewave": generate_squarewave, "one_squarewave": generate_one_squarewave,
    "sawtooth": generate_sawtooth, "harmonic": generate_harmonic,
    "sigmoid": generate_sigmoid, "mixed": generate_mixed,
}

def load_data(bsz, dataset_name, ctx_sz, fut_sz, res_x=0.1):
    generator = DATASET_GENERATORS[dataset_name]
    ctx_x_list, ctx_y_list, fut_x_list, fut_y_list = [], [], [], []
    for _ in range(bsz):
        gt_fn = generator()
        start_x = -2.5
        x_vals = start_x + np.arange(ctx_sz + fut_sz) * res_x
        y_vals = [float(gt_fn(x)) for x in x_vals]
        ctx_x_list.append(x_vals[:ctx_sz])
        ctx_y_list.append(y_vals[:ctx_sz])
        fut_x_list.append(x_vals[ctx_sz:])
        fut_y_list.append(y_vals[ctx_sz:])
    ctx_x = torch.tensor(ctx_x_list, dtype=torch.float32, device=device) * SCALE
    ctx_y = torch.tensor(ctx_y_list, dtype=torch.float32, device=device) * SCALE
    fut_x = torch.tensor(fut_x_list, dtype=torch.float32, device=device) * SCALE
    fut_y = torch.tensor(fut_y_list, dtype=torch.float32, device=device) * SCALE
    return ctx_x, ctx_y, fut_x, fut_y

"""Let's visualize a few sample signals to see what the task looks like."""

CTX_SZ = 10
FUT_SZ = 60

fig, axes = plt.subplots(1, 3, figsize=(16, 3))
for ax, name in zip(axes, ["one_line", "one_sinusoid", "one_squarewave"]):
    ctx_x, ctx_y, fut_x, fut_y = load_data(1, name, CTX_SZ, FUT_SZ)
    ax.plot(ctx_x[0].cpu(), ctx_y[0].cpu(), "b-", lw=2, label="Context")
    ax.plot(fut_x[0].cpu(), fut_y[0].cpu(), "b--", lw=2, label="Future (GT)")
    ax.set_title(name)
    ax.set_ylim([-2, 2])
axes[0].legend(fontsize=8)
plt.tight_layout()
plt.show()

"""## 3. Pretraining

Let $f_\theta: \mathbb{R}^{m} \to \mathbb{R}$, where `m = ctx_sz`.
For each sample, define

$$
\mathbf{c}=(y_0,\ldots,y_{m-1}), \qquad t=y_m.
$$

The model performs one-step prediction, $\hat t=f_\theta(\mathbf c)$, and minimizes MSE:

$$
\min_{\theta}\; \mathbb{E}_{(\mathbf c,t)\sim {D}_{\mathrm{pre}}}
\left[(f_\theta(\mathbf c)-t)^2\right].
$$

With batch size $B$:

$$
{L}_B(\theta)=\frac{1}{B}\sum_{b=1}^{B}
\left(f_\theta(\mathbf c^{(b)})-t^{(b)}\right)^2.
$$

Parameters are updated with Adam:

$$
\theta_{k+1}=\mathrm{Adam}\!\left(\theta_k,\nabla_\theta {L}_{B_k}(\theta_k),\eta\right).
$$
"""

def pretrain_base_model(model, pretrain_dataset, ctx_sz, fut_sz, bsz=256, iters=1000, lr=0.001):
    optimizer = torch.optim.Adam(model.parameters(), lr=lr)
    log_interval = max(1, iters // 10)
    t0 = time.time()
    for i in range(iters):
        model.train()
        optimizer.zero_grad()
        _, ctx_y, _, fut_y = load_data(bsz, pretrain_dataset, ctx_sz, fut_sz)
        loss = model.compute_loss(ctx_y, fut_y[:, [0]])
        loss.backward()
        optimizer.step()
        if i % log_interval == 0:
            print(f"  Iter {i+1}/{iters} - Loss: {loss.item():.4f}")
    print(f"  Pretraining done in {time.time() - t0:.1f}s")
    return model

"""## 4. RandOpt: The Core Algorithm

Let $\theta_0$ denote the base model weights.

For each sample, let $\mathbf{c} = (y_0, \dots, y_{m-1})$ be the context values and $\mathbf{y}_{1:T}$ be the next $T$ target values.

**Training**:

*1) Perturbation.* For each $i = 1, \dots, N$, sample a noise vector $\epsilon_i \sim {N}(0, I)$ and construct a perturbed model:

$$\theta_i = \theta_0 + \sigma \cdot \epsilon_i$$

where $\sigma > 0$ controls the perturbation magnitude.

*2)Evaluation.* Evaluate each perturbed model $\theta_i$ on a post-training dataset ${D}_{\text{post}}$ using autoregressive rollout, and compute its loss:

$${L}_i = \frac{1}{|{D}_{\text{post}}|} \sum_{(\mathbf{c}, \mathbf{y}_{1:T}) \in {D}_{\text{post}}} \left\| F^{\mathrm{AR}}_{\theta_i}(\mathbf{c}) - \mathbf{y}_{1:T} \right\|_2^2$$

where $F^{\mathrm{AR}}_{\theta_i}$ denotes multi-step autoregressive rollout.

*3) Selection.* Rank all $N$ perturbations by ${L}_i$ and select the top-$K$ with the lowest loss:

$$S = \operatorname{top_K}\bigl(\{(\theta_i, {L}_i)\}_{i=1}^{N}\bigr)$$

**Inference:**

At inference, average the rollout predictions of the top-$K$ models:

$${\mathbf{y}}^{\text{ensemble}}_{1:T}(\mathbf{c}) = \frac{1}{K} \sum_{\theta_j \in S} F^{\mathrm{AR}}_{\theta_j}(\mathbf{c})$$

Each perturbation is represented by its `(seed, sigma)` pair, so we store these instead of full model weights. In a fixed software/hardware setting, reseeding and reapplying noise reproduces the same perturbation.
"""

def compute_mse(y_pred, y_true):
    squared_error = ((y_pred - y_true) ** 2).flatten()
    mse = squared_error.mean()
    se = squared_error.std() / np.sqrt(squared_error.shape[0])
    return mse, se


def randopt(base_model, posttrain_dataset, ctx_sz, fut_sz, N=1000, sigma=0.05, K=5, dataset_sz=1024):
    """RandOpt: sample N perturbations, select top-K by loss on post-training data."""
    print(f"  Sampling {N} perturbations (sigma={sigma}), selecting top-{K}...")
    t0 = time.time()

    _, ctx_y, _, fut_y = load_data(dataset_sz, posttrain_dataset, ctx_sz, fut_sz)

    model_scores = []
    for seed in range(N):
        perturbed = copy.deepcopy(base_model)
        perturbed.perturb_weights(seed, sigma)
        perturbed.eval()
        with torch.no_grad():
            y_pred = perturbed.AR_rollout(ctx_y, fut_sz)
            # Calculate loss matching the formula: mean over batch, sum over time (L2 norm squared)
            loss = ((y_pred - fut_y) ** 2).sum(dim=1).mean()
        model_scores.append((seed, loss.item()))
        del perturbed

    model_scores.sort(key=lambda x: x[1])
    top_k_seeds = [model_scores[i][0] for i in range(K)]

    print(f"  Done in {time.time() - t0:.1f}s")
    print(f"  Best seed Loss: {model_scores[0][1]:.4f} | Worst of top-K: {model_scores[K-1][1]:.4f}")
    return top_k_seeds

"""## 5. Evaluation & Plotting"""

def evaluate_and_plot(base_model, top_k_seeds, sigma, ctx_sz, fut_sz, test_dataset,
                      test_bsz=256, num_random=25, title=""):
    """Evaluate base, top-K, ensemble, and random perturbations on test data."""
    ctx_x, ctx_y, fut_x, fut_y = load_data(test_bsz, test_dataset, ctx_sz, fut_sz)

    base_model.eval()
    with torch.no_grad():
        base_preds = base_model.AR_rollout(ctx_y, fut_sz)

        top_k_preds = []
        for seed in top_k_seeds:
            m = copy.deepcopy(base_model)
            m.perturb_weights(seed, sigma)
            m.eval()
            top_k_preds.append(m.AR_rollout(ctx_y, fut_sz))
            del m

        random_preds = []
        for _ in range(num_random):
            m = copy.deepcopy(base_model)
            m.perturb_weights(random.randint(0, 9999), sigma)
            m.eval()
            random_preds.append(m.AR_rollout(ctx_y, fut_sz))
            del m

        ensemble_preds = torch.stack(top_k_preds).mean(dim=0)

    base_mse, base_se = compute_mse(base_preds, fut_y)
    top1_mse, top1_se = compute_mse(top_k_preds[0], fut_y)
    ens_mse, ens_se = compute_mse(ensemble_preds, fut_y)

    print(f"  Base MSE:     {base_mse:.4f} +/- {base_se:.4f}")
    print(f"  Top-1 MSE:    {top1_mse:.4f} +/- {top1_se:.4f}")
    print(f"  Ensemble MSE: {ens_mse:.4f} +/- {ens_se:.4f}")

    fig, ax = plt.subplots(1, 1, figsize=(6, 5))
    idx = 0
    fx = fut_x[idx].cpu().numpy()
    for j, rp in enumerate(random_preds):
        label = "Random perturbs" if j == 0 else None
        ax.plot(fx, rp[idx].cpu().numpy(), "-", lw=1.0, alpha=0.15, c="gray", label=label)
    for j, kp in enumerate(top_k_preds):
        label = "Top-K perturbs" if j == 0 else None
        ax.plot(fx, kp[idx].cpu().numpy(), "-", lw=1.5, c=[0.85, 0.33, 0.25], label=label)
    ax.plot(fx, ensemble_preds[idx].cpu().numpy(), "-", lw=3.5, c=[0.941, 0.765, 0.157], label="Ensemble")
    ax.plot(fx, base_preds[idx].cpu().numpy(), "-", lw=3, c="k", label="Base model")
    ax.plot(ctx_x[idx].cpu().numpy(), ctx_y[idx].cpu().numpy(), "-", lw=3, c=[0.16, 0.44, 0.73], label="Context")
    ax.plot(fx, fut_y[idx].cpu().numpy(), "--", lw=3, c=[0.16, 0.44, 0.73], label="Ground truth")
    ax.set_ylim([-2 * SCALE, 2 * SCALE])
    ax.legend(fontsize=9, loc="lower left", ncol=2)
    fig.suptitle(title, fontsize=14, fontweight="bold")
    plt.tight_layout()
    plt.show()

    # --- Bar chart ---
    fig, ax = plt.subplots(figsize=(4, 5))
    bars = ["Base", "Top-1", "Ensemble"]
    vals = [base_mse.item(), top1_mse.item(), ens_mse.item()]
    errs = [base_se.item(), top1_se.item(), ens_se.item()]
    colors = ["k", [0.85, 0.33, 0.25], [0.941, 0.765, 0.157]]
    ax.bar(bars, vals, yerr=errs, capsize=5, color=colors)
    ax.set_ylabel("MSE +/- SE")
    ax.set_title(title)
    plt.tight_layout()
    plt.show()

    return {"base": base_mse.item(), "top1": top1_mse.item(), "ensemble": ens_mse.item()}

"""## 6. Run the Experiments

We run experiments to test whether RandOpt can find perturbations that approximate a target signal (`one_sinusoid`) under different base model conditions:

| Experiment | Base Model | Post-train | Test | Sigma |
|---|---|---|---|---|
| 1 | Xavier init (no pretraining) | `one_sinusoid` | `one_sinusoid` | 0.05 |
| 2 | Pretrained on `mixed` signals | `one_sinusoid` | `one_sinusoid` | 0.002 |
| 3 | Pretrained on `line` signals | `line` | `line` | 0.002 |
"""

GLOBAL_SEED = 0
N = 1000
K = 5
PRETRAIN_ITERS = 1000


EXPT_XAVIER_TO_SIN = {
    "name": "xavier -> one_sinusoid",
    "pretrain": None,
    "posttrain": "one_sinusoid",
    "test": "one_sinusoid",
    "init": "xavier",
    "sigma": 0.05,
}
EXPT_MIXED_TO_SIN = {
    "name": "mixed -> one_sinusoid",
    "pretrain": "mixed",
    "posttrain": "one_sinusoid",
    "test": "one_sinusoid",
    "init": "xavier",
    "sigma": 0.002,
}
EXPT_LINE_TO_LINE = {
    "name": "line -> line",
    "pretrain": "line",
    "posttrain": "line",
    "test": "line",
    "init": "kaiming init",
    "sigma": 0.002,
}

results = {}


def run_one_experiment(expt):
    posttrain_dataset = expt.get("posttrain", expt.get("target", "one_sinusoid"))
    test_dataset = expt.get("test", posttrain_dataset)

    print(f"\n{'='*60}")
    print(f"Experiment: {expt['name']}")
    print(f"Post-train dataset: {posttrain_dataset} | Test dataset: {test_dataset}")
    print(f"{'='*60}")

    random.seed(GLOBAL_SEED)
    np.random.seed(GLOBAL_SEED)
    torch.manual_seed(GLOBAL_SEED)

    base = Net(width=128, depth=5, dim_in=CTX_SZ, dim_out=1,
               init_type=expt["init"], device=device)
    base.init_weights()

    if expt["pretrain"] is not None:
        print(f"  Pretraining on '{expt['pretrain']}'...")
        base = pretrain_base_model(base, expt["pretrain"], CTX_SZ, FUT_SZ, iters=PRETRAIN_ITERS)

    top_k_seeds = randopt(base, posttrain_dataset, CTX_SZ, FUT_SZ,
                          N=N, sigma=expt["sigma"], K=K)

    res = evaluate_and_plot(base, top_k_seeds, expt["sigma"], CTX_SZ, FUT_SZ,
                            test_dataset, title=expt["name"])
    results[expt["name"]] = res
    return res

"""### Experiment 1: Needle in Haystack Regime
- **Setup:** no pretraining, Xavier initialization, perturbation scale: `sigma=0.05`.
- **Expected behavior:** small perturbations tend to have weak functional impact; strong solutions are far from this initialization.
"""

run_one_experiment(EXPT_XAVIER_TO_SIN)

"""### Experiment 2: Thicket Regime

- **Setup:** pretrain on `mixed` signal types, then RandOpt post-training on `one_sinusoid`.
- **Expected behavior:** perturbations search over many plausible continuations implied by pretraining.
"""

run_one_experiment(EXPT_MIXED_TO_SIN)

"""### Experiment 3: Plateau Regime

- **Setup:** pretrain on linear signals (`line`), then adapt toward `one_sinusoid`.
- **Expected behavior:** pretrained weights are already near a minimizer for test task, and random guessing can provide no further benefit.
"""

run_one_experiment(EXPT_LINE_TO_LINE)